name: HAWatchApp
options:
  bundleIdPrefix: com.hawatch
  deploymentTarget:
    watchOS: "26.0"
    iOS: "26.0"
  xcodeVersion: "26.0"
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  HAWatchCore:
    path: .

settings:
  base:
    SWIFT_VERSION: "6.2"
    CODE_SIGN_STYLE: Automatic

targets:

  # ── watchOS App ──────────────────────────────────────────────
  HAWatchApp:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: WatchApp
        excludes:
          - Widgets/**
    dependencies:
      - package: HAWatchCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hawatch.watchapp
        INFOPLIST_FILE: WatchApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: HA Watch
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
    entitlements:
      path: HAWatchApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.hawatch
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.hawatch
    info:
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.hawatch.deeplink
            CFBundleURLSchemes:
              - hawatch
        WKApplication: true
        WKBackgroundModes:
          - self-care

  # ── watchOS Widget Extension ─────────────────────────────────
  HAWatchWidgetExtension:
    type: app-extension
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: WatchApp/Widgets
      - path: WatchApp/Platform
    dependencies:
      - package: HAWatchCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hawatch.watchapp.widgets
        INFOPLIST_FILE: WatchApp/Widgets/Info.plist
        PRODUCT_NAME: HAWatchWidgets
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  # ── iOS Companion App ────────────────────────────────────────
  HAWatchCompanion:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: iPhoneApp
      - path: WatchApp/Platform
    dependencies:
      - package: HAWatchCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hawatch.companion
        INFOPLIST_FILE: iPhoneApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: HA Watch
        TARGETED_DEVICE_FAMILY: "1"
    entitlements:
      path: HAWatchCompanion.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.hawatch
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.hawatch
